dist: xenial
os: linux
language: generic
services:
  - docker

before_install:
  - docker build -t ocobas3/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ocobas3/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket: elasticbeanstalk-us-east-1-252572873180
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY